"""This module defines data parser
which can be used to exchange information between processes.
"""
import json
import abc
import shlex
import itertools
import enum

class ParseError(Exception):
    pass

class Parser:
    """Subclasses of this abstract class define
    how to input will be parsed.
    """

    @abc.abstractmethod
    def parse(self, line):
        """Parses a line.

        Args:
            line (str): read line

        Returns:
            dict containing the key value pairs of the line
        """
        raise NotImplementedError()

    @abc.abstractmethod
    def unparse(self, data):
        """Composes the data to a string
        whichs follows the syntax of the parser.

        Args:
            data (dict): data as key value pairs

        Returns:
            string
        """
        raise NotImplementedError()


class JsonParser(Parser):
    """Parses json input"""

    def parse(self, line):
        try:
            data = json.loads(line)
            if not isinstance(data, dict):
                raise ParseError(ValueError(
                    'Expected to parse an json object, got ' + line))
            return data
        except json.JSONDecodeError as error:
            raise ParseError(error)

    def unparse(self, data):
        return json.dumps(data)


class SimpleParser(Parser):
    """Parses key value pairs separated by a tab.
    Does not support escaping spaces.
    """
    SEPARATOR = '\t'

    def parse(self, line):
        components = line.split(SimpleParser.SEPARATOR)

        if len(components) % 2 != 0:
            raise ParseError(ValueError(
                'Expected key value pairs, ' +
                'but at least one key has no value: ' +
                line))

        return {
            key: value
            for key, value in itertools.zip_longest(
                components[::2], components[1::2])
        }

    def unparse(self, data):
        return SimpleParser.SEPARATOR.join(
            str(key) + SimpleParser.SEPARATOR + str(value.replace('\n', ''))
            for key, value in data.items())


class BashParser(Parser):
    """Parses input generated by dumping associated arrays with `declare -p`."""

    def parse(self, line):
        # remove 'typeset -A varname=( ' and ')'
        start = line.find('(')
        end = line.rfind(')')

        if not 0 <= start < end:
            raise ParseError(ValueError(
                "Expected input to be formatted like "
                "the output of bashs `declare -p` function. "
                "Got: " + line))

        components = itertools.dropwhile(
            lambda text: not text or text[0] != '[',
            shlex.split(line[start + 1:end]))
        return {
            key[1:-1]: value
            for pair in components
            for key, value in (pair.split('=', maxsplit=1),)
        }

    def unparse(self, data):
        return ' '.join(
            '[' + str(key) + ']=' + shlex.quote(value)
            for key, value in data.items())


@enum.unique
class ParserOption(str, enum.Enum):
    JSON = 'json', JsonParser
    SIMPLE = 'simple', SimpleParser
    BASH = 'bash', BashParser

    def __new__(cls, identifier, parser_class):
        inst = str.__new__(cls)
        inst._value_ = identifier
        inst.parser_class = parser_class
        return inst
